// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbRRjCkzBC5viMf1c8HuX--1NY4kr6p5o',
    appId: '1:61838838943:web:9f22f24411a9877593a6aa',
    messagingSenderId: '61838838943',
    projectId: 'act14-c4433',
    authDomain: 'act14-c4433.firebaseapp.com',
    storageBucket: 'act14-c4433.firebasestorage.app',
    measurementId: 'G-8DWSY0S5SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKD00PSX9KK7fTH5bLIvJBTwNTn4MUcxc',
    appId: '1:61838838943:android:0043c7fef41fa37693a6aa',
    messagingSenderId: '61838838943',
    projectId: 'act14-c4433',
    storageBucket: 'act14-c4433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzV6MNj7d92tW4tmbxS-mvc3eJ_W-L-DA',
    appId: '1:61838838943:ios:37a0eed5939c905f93a6aa',
    messagingSenderId: '61838838943',
    projectId: 'act14-c4433',
    storageBucket: 'act14-c4433.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzV6MNj7d92tW4tmbxS-mvc3eJ_W-L-DA',
    appId: '1:61838838943:ios:37a0eed5939c905f93a6aa',
    messagingSenderId: '61838838943',
    projectId: 'act14-c4433',
    storageBucket: 'act14-c4433.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbRRjCkzBC5viMf1c8HuX--1NY4kr6p5o',
    appId: '1:61838838943:web:00e3b34e1c9f598a93a6aa',
    messagingSenderId: '61838838943',
    projectId: 'act14-c4433',
    authDomain: 'act14-c4433.firebaseapp.com',
    storageBucket: 'act14-c4433.firebasestorage.app',
    measurementId: 'G-BFLQMD0SQT',
  );
}
